### ISSUE TITLE
Need upgrade the cache dependency version

### ISSUE THREAD

**Issue by LittleOrchid** [letmutx/dex-parser#42]
Run the dexparser with rustc(1.50.0), I got a crash in the cache module. I solved this problem with upgrading the cache dependency to v0.2.0.

**Comment by letmutx** [comment]
Can you post a stack trace for the crash (along with a sample input, if possible) please? If you're up for it, feel free to raise a PR with a fix. I'll be happy to merge and release.

**Comment by meme** [comment]
https://github.com/letmutx/dex-parser/pull/43
